DROP INDEX PK_FAQ0;

/* 자주묻는질문 */
DROP TABLE FAQ0 
	CASCADE CONSTRAINTS;

/* 자주묻는질문 */
CREATE TABLE FAQ0 (
	fNO NUMBER(5) NOT NULL, /* 글번호 */
	fTITLE VARCHAR2(255 CHAR) NOT NULL, /* 제목 */
	fCONTENT CLOB NOT NULL, /* 내용 */
	fRDATE DATE NOT NULL /* 등록일 */
);

CREATE UNIQUE INDEX PK_FAQ0
	ON FAQ0 (
		fNO ASC
	);

ALTER TABLE FAQ0
	ADD
		CONSTRAINT PK_FAQ0
		PRIMARY KEY (
			fNO
		);

DROP INDEX PK_MEMBER0;

/* 고객 */
DROP TABLE MEMBER0 
	CASCADE CONSTRAINTS;

/* 고객 */
CREATE TABLE MEMBER0 (
	mID VARCHAR2(50 CHAR) NOT NULL, /* 고객아이디 */
	mPW VARCHAR2(50 CHAR) NOT NULL, /* 비밀번호 */
	mNAME VARCHAR2(50 CHAR) NOT NULL, /* 이름 */
	mPOST NUMBER(5) NOT NULL, /* 우편번호 */
	mADD VARCHAR2(500 CHAR) NOT NULL, /* 주소 */
	mADD2 VARCHAR2(500 CHAR) NOT NULL, /* 상세주소 */
	mPHONE VARCHAR2(20 CHAR) NOT NULL, /* 휴대폰번호 */
	mEMAIL VARCHAR2(500 CHAR) NOT NULL, /* 이메일 */
	mRDATE DATE NOT NULL /* 가입일 */
);

CREATE UNIQUE INDEX PK_MEMBER0
	ON MEMBER0 (
		mID ASC
	);

ALTER TABLE MEMBER0
	ADD
		CONSTRAINT PK_MEMBER0
		PRIMARY KEY (
			mID
		);

DROP INDEX PK_PRODUCT0;

/* 제품 */
DROP TABLE PRODUCT0 
	CASCADE CONSTRAINTS;

/* 제품 */
CREATE TABLE PRODUCT0 (
	pNO NUMBER(5) NOT NULL, /* 상품번호 */
	pNAME VARCHAR2(100 CHAR) NOT NULL, /* 상품명 */
	pTYPE VARCHAR2(50 CHAR) NOT NULL, /* 종류 */
	pPRICE NUMBER(8) NOT NULL, /* 가격 */
	pIMG VARCHAR2(500 CHAR), /* 이미지 */
	pDETAIL CLOB NOT NULL, /* 상세정보 */
	pRDATE DATE NOT NULL /* 등록일 */
);

CREATE UNIQUE INDEX PK_PRODUCT0
	ON PRODUCT0 (
		pNO ASC
	);

ALTER TABLE PRODUCT0
	ADD
		CONSTRAINT PK_PRODUCT0
		PRIMARY KEY (
			pNO
		);
		
DROP INDEX PK_QNA0;

/* 질문게시판 */
DROP TABLE QNA0 
	CASCADE CONSTRAINTS;

/* 질문게시판 */
CREATE TABLE QNA0 (
	qNO NUMBER(5) NOT NULL, /* 질문번호 */
	mID VARCHAR2(50 CHAR) NOT NULL, /* 고객아이디 */
	qTITLE VARCHAR2(255 CHAR) NOT NULL, /* 질문제목 */
	qCONTENT CLOB NOT NULL, /* 질문내용 */
	qIMG VARCHAR2(500 CHAR), /* 이미지 */
	qRDATE DATE NOT NULL, /* 등록일 */
	qREAD NUMBER(5) NOT NULL /* 조회수 */
);

CREATE UNIQUE INDEX PK_QNA0
	ON QNA0 (
		qNO ASC
	);

ALTER TABLE QNA0
	ADD
		CONSTRAINT PK_QNA0
		PRIMARY KEY (
			qNO
		);

ALTER TABLE QNA0
	ADD
		CONSTRAINT FK_MEMBER0_TO_QNA0
		FOREIGN KEY (
			mID
		)
		REFERENCES MEMBER0 (
			mID
		);
		
DROP INDEX PK_REVIEW0;

/* 리뷰 */
DROP TABLE REVIEW0 
	CASCADE CONSTRAINTS;

/* 리뷰 */
CREATE TABLE REVIEW0 (
	rNO NUMBER(5) NOT NULL, /* 리뷰번호 */
	mID VARCHAR2(50 CHAR) NOT NULL, /* 고객아이디 */
	pNO NUMBER(5) NOT NULL, /* 상품번호 */
	rTITLE VARCHAR2(255 CHAR) NOT NULL, /* 리뷰제목 */
	rCONTENT CLOB NOT NULL, /* 리뷰내용 */
	rRDATE DATE NOT NULL, /* 등록일 */
	rIMG VARCHAR2(500 CHAR) /* 리뷰사진 */
);

CREATE UNIQUE INDEX PK_REVIEW0
	ON REVIEW0 (
		rNO ASC
	);

ALTER TABLE REVIEW0
	ADD
		CONSTRAINT PK_REVIEW0
		PRIMARY KEY (
			rNO
		);

ALTER TABLE REVIEW0
	ADD
		CONSTRAINT FK_MEMBER0_TO_REVIEW0
		FOREIGN KEY (
			mID
		)
		REFERENCES MEMBER0 (
			mID
		);

ALTER TABLE REVIEW0
	ADD
		CONSTRAINT FK_PRODUCT0_TO_REVIEW0
		FOREIGN KEY (
			pNO
		)
		REFERENCES PRODUCT0 (
			pNO
		);
		
DROP INDEX PK_CART0;

/* 카트 */
DROP TABLE CART0 
	CASCADE CONSTRAINTS;

/* 카트 */
CREATE TABLE CART0 (
	cNO NUMBER(5) NOT NULL, /* 카트번호 */
	cQTY NUMBER(3) NOT NULL, /* 구매수량 */
	mID VARCHAR2(50 CHAR) NOT NULL, /* 고객아이디 */
	pNO NUMBER(5) NOT NULL /* 상품번호 */
);

CREATE UNIQUE INDEX PK_CART0
	ON CART0 (
		cNO ASC
	);

ALTER TABLE CART0
	ADD
		CONSTRAINT PK_CART0
		PRIMARY KEY (
			cNO
		);

ALTER TABLE CART0
	ADD
		CONSTRAINT FK_MEMBER0_TO_CART0
		FOREIGN KEY (
			mID
		)
		REFERENCES MEMBER0 (
			mID
		);

ALTER TABLE CART0
	ADD
		CONSTRAINT FK_PRODUCT0_TO_CART0
		FOREIGN KEY (
			pNO
		)
		REFERENCES PRODUCT0 (
			pNO
		);

DROP INDEX PK_ORDERS0;

/* 오더 */
DROP TABLE ORDERS0 
	CASCADE CONSTRAINTS;

/* 오더 */
CREATE TABLE ORDERS0 (
	oNO NUMBER(5) NOT NULL, /* 오더번호 */
	mID VARCHAR2(50 CHAR), /* 고객아이디 */
	oRDATE DATE NOT NULL, /* 주문일 */
	oNAME VARCHAR2(50 CHAR) NOT NULL, /* 수령자 */
	oPHONE VARCHAR2(20 CHAR) NOT NULL, /* 수령자연락처 */
	oADD VARCHAR2(500 CHAR) NOT NULL, /* 수령자주소 */
	oADD2 VARCHAR2(500 CHAR) NOT NULL, /* 상세주소 */
	oPOST NUMBER(5) NOT NULL, /* 수령자우편번호 */
	oPRICE NUMBER(8) NOT NULL, /* 오더총금액 */
	oSTATE NUMBER(1) NOT NULL, /* 배송상태 */
	oPAY NUMBER(1) NOT NULL /* 결제수단 */
);

CREATE UNIQUE INDEX PK_ORDERS0
	ON ORDERS0 (
		oNO ASC
	);

ALTER TABLE ORDERS0
	ADD
		CONSTRAINT PK_ORDERS0
		PRIMARY KEY (
			oNO
		);

ALTER TABLE ORDERS0
	ADD
		CONSTRAINT FK_MEMBER0_TO_ORDERS0
		FOREIGN KEY (
			mID
		)
		REFERENCES MEMBER0 (
			mID
		);
		
DROP INDEX PK_ORDERS_DETAIL0;

/* 오더디테일 */
DROP TABLE ORDERS_DETAIL0 
	CASCADE CONSTRAINTS;

/* 오더디테일 */
CREATE TABLE ORDERS_DETAIL0 (
	odNO NUMBER(5) NOT NULL, /* 오더상세번호 */
	pNO NUMBER(5) NOT NULL, /* 상품번호 */
	oNO NUMBER(5) NOT NULL, /* 오더번호 */
	odQTY NUMBER(3) NOT NULL /* 상품별구매수량 */
);

CREATE UNIQUE INDEX PK_ORDERS_DETAIL0
	ON ORDERS_DETAIL0 (
		odNO ASC
	);

ALTER TABLE ORDERS_DETAIL0
	ADD
		CONSTRAINT PK_ORDERS_DETAIL0
		PRIMARY KEY (
			odNO
		);

ALTER TABLE ORDERS_DETAIL0
	ADD
		CONSTRAINT FK_PRODUCT0_TO_ORDERS_DETAIL0
		FOREIGN KEY (
			pNO
		)
		REFERENCES PRODUCT0 (
			pNO
		);

ALTER TABLE ORDERS_DETAIL0
	ADD
		CONSTRAINT FK_ORDERS0_TO_ORDERS_DETAIL0
		FOREIGN KEY (
			oNO
		)
		REFERENCES ORDERS0 (
			oNO
		);
		
DROP INDEX PK_QNA0;

/* 질문게시판 */
DROP TABLE QNA0 
	CASCADE CONSTRAINTS;

/* 질문게시판 */
CREATE TABLE QNA0 (
	qNO NUMBER(5) NOT NULL, /* 질문번호 */
	mID VARCHAR2(50 CHAR) NOT NULL, /* 고객아이디 */
	qTITLE VARCHAR2(255 CHAR) NOT NULL, /* 질문제목 */
	qCONTENT CLOB NOT NULL, /* 질문내용 */
	qRDATE DATE NOT NULL /* 등록일 */
);

CREATE UNIQUE INDEX PK_QNA0
	ON QNA0 (
		qNO ASC
	);

ALTER TABLE QNA0
	ADD
		CONSTRAINT PK_QNA0
		PRIMARY KEY (
			qNO
		);

ALTER TABLE QNA0
	ADD
		CONSTRAINT FK_MEMBER0_TO_QNA0
		FOREIGN KEY (
			mID
		)
		REFERENCES MEMBER0 (
			mID
		);
		
DROP INDEX PK_NOTICE0;

/* 공지사항 */
DROP TABLE NOTICE0 
	CASCADE CONSTRAINTS;

/* 공지사항 */
CREATE TABLE NOTICE0 (
	nNO NUMBER(5) NOT NULL, /* 공지글번호 */
	nTITLE VARCHAR2(255 CHAR) NOT NULL, /* 제목 */
	nCONTENT CLOB NOT NULL, /* 내용 */
	nRDATE DATE NOT NULL /* 등록일 */
);

CREATE UNIQUE INDEX PK_NOTICE0
	ON NOTICE0 (
		nNO ASC
	);

ALTER TABLE NOTICE0
	ADD
		CONSTRAINT PK_NOTICE0
		PRIMARY KEY (
			nNO
		);

DROP INDEX PK_QNA_REPLY0;

/* 질문게시판답 */
DROP TABLE QNA_REPLY0 
	CASCADE CONSTRAINTS;

/* 질문게시판답 */
CREATE TABLE QNA_REPLY0 (
	qrNO NUMBER(5) NOT NULL, /* 답변번호 */
	qNO NUMBER(5) NOT NULL, /* 질문번호 */
	qrTITLE VARCHAR2(255 CHAR) NOT NULL, /* 답변제목 */
	qrCONTENT CLOB NOT NULL, /* 답변내용 */
	qrRDATE DATE NOT NULL /* 등록일 */
);

CREATE UNIQUE INDEX PK_QNA_REPLY0
	ON QNA_REPLY0 (
		qrNO ASC
	);

ALTER TABLE QNA_REPLY0
	ADD
		CONSTRAINT PK_QNA_REPLY0
		PRIMARY KEY (
			qrNO
		);

ALTER TABLE QNA_REPLY0
	ADD
		CONSTRAINT FK_QNA0_TO_QNA_REPLY0
		FOREIGN KEY (
			qNO
		)
		REFERENCES QNA0 (
			qNO
		);
		
DROP SEQUENCE QNA0_SEQ;
CREATE SEQUENCE QNA0_SEQ;
DROP SEQUENCE ORDERS0_SEQ;
CREATE SEQUENCE ORDERS0_SEQ;
DROP SEQUENCE REVIEW0_SEQ;
CREATE SEQUENCE REVIEW0_SEQ;
DROP SEQUENCE CART0_SEQ;
CREATE SEQUENCE CART0_SEQ;
DROP SEQUENCE ORDERS_DETAIL0_SEQ;
CREATE SEQUENCE ORDERS_DETAIL0_SEQ;
DROP SEQUENCE FAQ0_SEQ;
CREATE SEQUENCE FAQ0_SEQ;
DROP SEQUENCE NOTICE0_SEQ;
CREATE SEQUENCE NOTICE0_SEQ;
DROP SEQUENCE PRODUCT0_SEQ;
CREATE SEQUENCE PRODUCT0_SEQ;
DROP SEQUENCE QNA_REPLY0_SEQ;
CREATE SEQUENCE QNA_REPLY0_SEQ;
COMMIT;